version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subsonic-client
    restart: unless-stopped
    ports:
      - "${PORT:-80}:80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.subsonic-client.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.services.subsonic-client.loadbalancer.server.port=80"